// Copyright 2023 PolyCrypt GmbH
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package wire_test

import (
	"fmt"
	"github.com/stretchr/testify/require"
	"perun.network/perun-stellar-backend/wire"
	"testing"
)

func TestBalances(t *testing.T) {
	// Balances XDR generated by soroban contract
	x := []byte{0, 0, 0, 17, 0, 0, 0, 1, 0, 0, 0, 3, 0, 0, 0, 15, 0, 0, 0, 5, 98, 97, 108, 95, 97, 0, 0, 0, 0, 0, 0, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 15, 0, 0, 0, 5, 98, 97, 108, 95, 98, 0, 0, 0, 0, 0, 0, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 15, 0, 0, 0, 5, 116, 111, 107, 101, 110, 0, 0, 0, 0, 0, 0, 18, 0, 0, 0, 1, 206, 189, 184, 3, 222, 31, 3, 119, 148, 96, 26, 56, 67, 233, 206, 144, 53, 117, 109, 200, 172, 60, 79, 190, 69, 198, 194, 72, 127, 57, 239, 18}
	balances := &wire.Balances{}
	err := balances.UnmarshalBinary(x)
	require.NoError(t, err)
	fmt.Println(balances)
	res, err := balances.MarshalBinary()
	require.NoError(t, err)
	require.Equal(t, x, res)
}
