// Copyright 2024 PolyCrypt GmbH
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package wire_test

import (
	"fmt"
	"github.com/stretchr/testify/require"
	"perun.network/perun-stellar-backend/wire"
	"testing"
)

func TestBalances(t *testing.T) {
	// Balances XDR generated by soroban contract
	x := []byte{0, 0, 0, 17, 0, 0, 0, 1, 0, 0, 0, 3, 0, 0, 0, 15, 0, 0, 0, 5, 98, 97, 108, 95, 97, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 100, 0, 0, 0, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 150, 0, 0, 0, 15, 0, 0, 0, 5, 98, 97, 108, 95, 98, 0, 0, 0, 0, 0, 0, 16, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 200, 0, 0, 0, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 250, 0, 0, 0, 15, 0, 0, 0, 6, 116, 111, 107, 101, 110, 115, 0, 0, 0, 0, 0, 16, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 18, 0, 0, 0, 1, 128, 17, 187, 244, 205, 240, 78, 91, 198, 172, 136, 105, 53, 185, 154, 164, 178, 192, 202, 189, 225, 51, 249, 215, 251, 62, 101, 103, 153, 240, 168, 150, 0, 0, 0, 18, 0, 0, 0, 1, 4, 202, 219, 74, 87, 15, 210, 228, 101, 46,
		129, 65, 1, 80, 153, 18, 204, 230, 201, 162, 50, 93, 110, 236, 141, 113, 0, 202, 248, 89, 243, 224}
	balances := &wire.Balances{}
	err := balances.UnmarshalBinary(x)
	require.NoError(t, err)
	fmt.Println(balances)
	res, err := balances.MarshalBinary()
	require.NoError(t, err)
	require.Equal(t, x, res)
}
