name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.22'

    - name: Run GolangCI-Lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.54.2
        args: --timeout=5m

    - name: Run unit tests
      run: go test ./...

    - name: Build Docker Image using build.sh
      run: |
          chmod +x ./testdata/docker/build.sh
          ./testdata/docker/build.sh


    - name: Run quickstart.sh script
      run: |
            chmod +x ./quickstart.sh
            ./quickstart.sh standalone &
            
    - name: Wait for local chain setup
      run: sleep 50

    - name: Run integration tests
      run: go test -tags=integration -p 1 ./channel ./payment

    - name: Stop local chain
      run: docker stop stellar
